#!/usr/bin/env python

from sys import argv
import hw_organizer
import hw_grader

def main() -> None:
    usage_message = 'Usage: ista-hw -m (for making the filesystem) OR ista_hw -g (for grading)'
    if len(argv) != 2:
        print(usage_message)
    elif argv[1] == '-m':
        hw_organizer.main()
    elif argv[1] == '-g':
        hw_grader.main()
    else:
        print(usage_message)
        
if __name__ == '__main__':
    main()
